#!/bin/bash
sdb 'db=new Sdb("localhost",11810,"sdbadmin","sdbadmin")'

sdb 'db.getCataRG().reelect( {Hostname: "u16-jqq"} )'
sdb 'db.getRG("group1").reelect({HostName:"u16-jqq"})'
sdb 'db.getRG("group2").reelect({HostName:"c79-jiangqiqian"})'
sdb 'db.getRG("group3").reelect({HostName:"u22-wgl"})'
sdb 'db.snapshot(12,{IsPrimary:true},{NodeName:""})' 

# sdb 'db.getCataRG().reelect( {Hostname: "ecmsdb16"} )'
# sdb 'db.getRG("group1").reelect({HostName:"ecmsdb10"})'
# sdb 'db.getRG("group2").reelect({HostName:"ecmsdb10"})'
# sdb 'db.getRG("group3").reelect({HostName:"ecmsdb10"})'
# sdb 'db.getRG("group4").reelect({HostName:"ecmsdb10"})'
# sdb 'db.getRG("group5").reelect({HostName:"ecmsdb10"})'
# sdb 'db.getRG("group6").reelect({HostName:"ecmsdb10"})'
# sdb 'db.getRG("group7").reelect({HostName:"ecmsdb13"})'
# sdb 'db.getRG("group8").reelect({HostName:"ecmsdb13"})'
# sdb 'db.getRG("group9").reelect({HostName:"ecmsdb13"})'
# sdb 'db.getRG("group10").reelect({HostName:"ecmsdb13"})'
# sdb 'db.getRG("group11").reelect({HostName:"ecmsdb13"})'
# sdb 'db.getRG("group12").reelect({HostName:"ecmsdb13"})'

# sdb 'db.getRG("group13").reelect({HostName:"ecmsdb11"})'
# sdb 'db.getRG("group14").reelect({HostName:"ecmsdb11"})'
# sdb 'db.getRG("group15").reelect({HostName:"ecmsdb11"})'
# sdb 'db.getRG("group16").reelect({HostName:"ecmsdb11"})'
# sdb 'db.getRG("group17").reelect({HostName:"ecmsdb11"})'
# sdb 'db.getRG("group18").reelect({HostName:"ecmsdb11"})'
# sdb 'db.getRG("group19").reelect({HostName:"ecmsdb14"})'
# sdb 'db.getRG("group20").reelect({HostName:"ecmsdb14"})'
# sdb 'db.getRG("group21").reelect({HostName:"ecmsdb14"})'
# sdb 'db.getRG("group22").reelect({HostName:"ecmsdb14"})'
# sdb 'db.getRG("group23").reelect({HostName:"ecmsdb14"})'
# sdb 'db.getRG("group24").reelect({HostName:"ecmsdb14"})'

# sdb 'db.getRG("group25").reelect({HostName:"ecmsdb12"})'
# sdb 'db.getRG("group26").reelect({HostName:"ecmsdb12"})'
# sdb 'db.getRG("group27").reelect({HostName:"ecmsdb12"})'
# sdb 'db.getRG("group28").reelect({HostName:"ecmsdb12"})'
# sdb 'db.getRG("group29").reelect({HostName:"ecmsdb12"})'
# sdb 'db.getRG("group30").reelect({HostName:"ecmsdb12"})'
# sdb 'db.getRG("group31").reelect({HostName:"ecmsdb15"})'
# sdb 'db.getRG("group32").reelect({HostName:"ecmsdb15"})'
# sdb 'db.getRG("group33").reelect({HostName:"ecmsdb15"})'
# sdb 'db.getRG("group34").reelect({HostName:"ecmsdb15"})'
# sdb 'db.getRG("group35").reelect({HostName:"ecmsdb15"})'
# sdb 'db.getRG("group36").reelect({HostName:"ecmsdb15"})'

# sdb 'db.getRG("group37").reelect({HostName:"ecmsdb19"})'
# sdb 'db.getRG("group38").reelect({HostName:"ecmsdb19"})'
# sdb 'db.getRG("group39").reelect({HostName:"ecmsdb19"})'
# sdb 'db.getRG("group40").reelect({HostName:"ecmsdb19"})'
# sdb 'db.getRG("group41").reelect({HostName:"ecmsdb19"})'
# sdb 'db.getRG("group42").reelect({HostName:"ecmsdb19"})'
# sdb 'db.getRG("group43").reelect({HostName:"ecmsdb22"})'
# sdb 'db.getRG("group44").reelect({HostName:"ecmsdb22"})'
# sdb 'db.getRG("group45").reelect({HostName:"ecmsdb22"})'
# sdb 'db.getRG("group46").reelect({HostName:"ecmsdb22"})'
# sdb 'db.getRG("group47").reelect({HostName:"ecmsdb22"})'
# sdb 'db.getRG("group48").reelect({HostName:"ecmsdb22"})'

# sdb 'db.getRG("group49").reelect({HostName:"ecmsdb20"})'
# sdb 'db.getRG("group50").reelect({HostName:"ecmsdb20"})'
# sdb 'db.getRG("group51").reelect({HostName:"ecmsdb20"})'
# sdb 'db.getRG("group52").reelect({HostName:"ecmsdb20"})'
# sdb 'db.getRG("group53").reelect({HostName:"ecmsdb20"})'
# sdb 'db.getRG("group54").reelect({HostName:"ecmsdb20"})'
# sdb 'db.getRG("group55").reelect({HostName:"ecmsdb23"})'
# sdb 'db.getRG("group56").reelect({HostName:"ecmsdb23"})'
# sdb 'db.getRG("group57").reelect({HostName:"ecmsdb23"})'
# sdb 'db.getRG("group58").reelect({HostName:"ecmsdb23"})'
# sdb 'db.getRG("group59").reelect({HostName:"ecmsdb23"})'
# sdb 'db.getRG("group60").reelect({HostName:"ecmsdb23"})'

# sdb 'db.getRG("group61").reelect({HostName:"ecmsdb21"})'
# sdb 'db.getRG("group62").reelect({HostName:"ecmsdb21"})'
# sdb 'db.getRG("group63").reelect({HostName:"ecmsdb21"})'
# sdb 'db.getRG("group64").reelect({HostName:"ecmsdb21"})'
# sdb 'db.getRG("group65").reelect({HostName:"ecmsdb21"})'
# sdb 'db.getRG("group66").reelect({HostName:"ecmsdb21"})'
# sdb 'db.getRG("group67").reelect({HostName:"ecmsdb24"})'
# sdb 'db.getRG("group68").reelect({HostName:"ecmsdb24"})'
# sdb 'db.getRG("group69").reelect({HostName:"ecmsdb24"})'
# sdb 'db.getRG("group70").reelect({HostName:"ecmsdb24"})'
# sdb 'db.getRG("group71").reelect({HostName:"ecmsdb24"})'
# sdb 'db.getRG("group72").reelect({HostName:"ecmsdb24"})'

# sdb 'db.getRG("group73").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group74").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group75").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group76").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group77").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group78").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group79").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group80").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group81").reelect({HostName:"ecmsdb28"})'
# sdb 'db.getRG("group82").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group83").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group84").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group85").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group86").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group87").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group88").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group89").reelect({HostName:"ecmsdb29"})'
# sdb 'db.getRG("group90").reelect({HostName:"ecmsdb29"})'

# sdb 'db.getRG("group91").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group92").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group93").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group94").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group95").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group96").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group97").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group98").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group99").reelect({HostName:"ecmsdb31"})'
# sdb 'db.getRG("group100").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group101").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group102").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group103").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group104").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group105").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group106").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group107").reelect({HostName:"ecmsdb32"})'
# sdb 'db.getRG("group108").reelect({HostName:"ecmsdb32"})'

# sdb 'db.getRG("group109").reelect({HostName:"ecmsdb34"})'
# sdb 'db.getRG("group110").reelect({HostName:"ecmsdb34"})'
# sdb 'db.getRG("group111").reelect({HostName:"ecmsdb34"})'
# sdb 'db.getRG("group112").reelect({HostName:"ecmsdb35"})'
# sdb 'db.getRG("group113").reelect({HostName:"ecmsdb35"})'
# sdb 'db.getRG("group114").reelect({HostName:"ecmsdb35"})'
# sdb 'db.getRG("group115").reelect({HostName:"ecmsdb36"})'
# sdb 'db.getRG("group116").reelect({HostName:"ecmsdb36"})'
# sdb 'db.getRG("group117").reelect({HostName:"ecmsdb36"})'

# sdb 'db.getRG("group118").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group119").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group120").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group121").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group122").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group123").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group124").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group125").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group126").reelect({HostName:"ecmsdb37"})'
# sdb 'db.getRG("group127").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group128").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group129").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group130").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group131").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group132").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group133").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group134").reelect({HostName:"ecmsdb38"})'
# sdb 'db.getRG("group135").reelect({HostName:"ecmsdb38"})'

# sdb 'db.getRG("group136").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group137").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group138").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group139").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group140").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group141").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group142").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group143").reelect({HostName:"ecmsdb40"})'
# sdb 'db.getRG("group144").reelect({HostName:"ecmsdb40"})'

# sdb 'db.getRG("group145").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group146").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group147").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group148").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group149").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group150").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group151").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group152").reelect({HostName:"ecmsdb41"})'
# sdb 'db.getRG("group153").reelect({HostName:"ecmsdb41"})'

# sdb 'db.snapshot(12,{IsPrimary:true},{NodeName:""})' 
